### PR TITLE
Feature/remove hal

### LINKED ISSUE #184: Update API to match S1

### PR DESCRIPTION
**Pull request by manuwei**
#### Short Description
Remove all Hal links and add Learning Method Entity

#### Proposed Changes
  * remove all hal links (this changes the response format of all returned entities)
  * remove all logic for creating the hal links (linkassemblers)
  * add LearningMethod entity
  * delete root mapping

This PR closes #184

### CODE REVIEW

**Review by lharzenetter — CHANGES_REQUESTED** [review]
In genereal it looks good. Please add the lisence headers for new files and also update the altered files to contain the new year. For exmaple `Copyright (c) 2020-2021 the qc-atlas contributors.`.

**Review by salmma — CHANGES_REQUESTED** [review]
Please consider & fix the few checkstyle warnings and errors :)
seen by executing `mvn package -DskipTests`

**Comment by manuwei** [comment]
I fixed the error detected by mvn package & included the requested changes of @lharzenetter as well

**Review by salmma — APPROVED** [review]
no more warnings - LGTM

**Review by lharzenetter — APPROVED** [review]

**Pull request merged**
